/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.fi.muni.pa165.hotelbookingmanagerdesktop;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author FILIP
 */
public class HotelDialog extends javax.swing.JDialog {

    /**
     * Creates new form hotelDialog
     */
    public HotelDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initializeCountryPicker();
    }
    
    public HotelDialog(String name, String address, String city, String country, String telephone, String email){
        initComponents();
        initializeCountryPicker();
        hotelNameField.setText(name);        
        hotelAddressField.setText(address);
        hotelCityField.setText(city);
        hotelCountryComboBox.setSelectedItem(country);
        hotelTelephoneField.setText(telephone);
        hotelEmailField.setText(email);
    }

    private void initializeCountryPicker() {
        List<String> countries = new ArrayList<>();

        Locale[] locales = Locale.getAvailableLocales();
        for (Locale locale : locales) {
            String countryName = locale.getDisplayCountry();
            if (!countryName.isEmpty()) {
                countries.add(countryName);
            }
        }
        Collections.sort(countries);
        for (String s : countries) {
            hotelCountryComboBox.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hotelNameField = new javax.swing.JTextField();
        hotelAddressField = new javax.swing.JTextField();
        hotelCityField = new javax.swing.JTextField();
        hotelTelephoneField = new javax.swing.JTextField();
        hotelEmailField = new javax.swing.JTextField();
        hotelCountryComboBox = new javax.swing.JComboBox();
        hotelCancelButton = new javax.swing.JButton();
        hotelCreateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Create new hotel");

        jLabel2.setText("Name");

        jLabel3.setText("Contact Information :");

        jLabel4.setText("Address");

        jLabel5.setText("City");

        jLabel6.setText("Country");

        jLabel7.setText("Telephone");

        jLabel8.setText("Email");

        hotelNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelNameFieldActionPerformed(evt);
            }
        });

        hotelCancelButton.setText("Cancel");
        hotelCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelCancelButtonActionPerformed(evt);
            }
        });

        hotelCreateButton.setText("Create");
        hotelCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelCreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hotelCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hotelCreateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hotelNameField)
                                    .addComponent(hotelAddressField)
                                    .addComponent(hotelCityField)
                                    .addComponent(hotelTelephoneField)
                                    .addComponent(hotelEmailField)
                                    .addComponent(hotelCountryComboBox, 0, 153, Short.MAX_VALUE))))
                        .addGap(0, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hotelNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hotelAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hotelCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hotelCountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(hotelTelephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hotelEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelCancelButton)
                    .addComponent(hotelCreateButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotelNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelNameFieldActionPerformed

    private void hotelCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelCancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_hotelCancelButtonActionPerformed

    private void hotelCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelCreateButtonActionPerformed
      if(validateInformation()){
        //TODO - Send requests to server AND update main frame
      }
    }//GEN-LAST:event_hotelCreateButtonActionPerformed

    private boolean validateInformation() {
        String errors = "";
        if (hotelNameField.getText().isEmpty()) {
            errors += "First name is a required field.\n";
        }        
        if (hotelAddressField.getText().isEmpty()) {
            errors += "Address field is a required field.\n";
        }
        if (hotelCityField.getText().isEmpty()) {
            errors += "City field is a required field.\n";
        }
        if (hotelTelephoneField.getText().isEmpty()) {
            errors += "Telephone field is a required field.\n";
        } else if (!hotelTelephoneField.getText().matches("\\d+")) {
            errors += "Invalid telephone number.\n";
        }
        if (hotelEmailField.getText().isEmpty()) {
            errors += "Email field is a required field.\n";
        } else if (!hotelEmailField.getText().matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$")) {
            errors += "Invalid email address.\n";
        }
        if (errors.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, errors, "Errors found", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HotelDialog dialog = new HotelDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hotelAddressField;
    private javax.swing.JButton hotelCancelButton;
    private javax.swing.JTextField hotelCityField;
    private javax.swing.JComboBox hotelCountryComboBox;
    private javax.swing.JButton hotelCreateButton;
    private javax.swing.JTextField hotelEmailField;
    private javax.swing.JTextField hotelNameField;
    private javax.swing.JTextField hotelTelephoneField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
